name: nutri_tracker
description: App de rastreamento de calorias com IA

environment:
  sdk: ^3.9.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  google_generative_ai: ^0.4.3
  image_picker: ^1.0.4
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  intl: ^0.19.0
  fl_chart: ^0.64.0
  camera: ^0.10.5
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
